### PR TITLE
[JENKINS-40193] pom upgraded

### PR DESCRIPTION
**Pull request by escoem**
hey @zhaozhiming I think should work, just need to merge and mvn release:prepare release:perform

### CODE REVIEW

**Comment by escoem** [comment]
I missed one file

**Comment by zhaozhiming** [comment]
LGTM

**Comment by zhaozhiming** [comment]
@escoem It seems something wrong. When I upload files it report error message:  `401, ReasonPhrase: Unauthorized`.

**Comment by escoem** [comment]
Hi @zhaozhiming give a look at https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org

**Pull request merged**
